fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
    body_converter:
        enabled: true
    param_fetcher_listener: force        
    body_listener: true
    #serializer:
        #serialize_null: true
    exception:
        enabled: true
        codes:
            # Sogedial\ApiBundle\Exception\EntityNotFoundException: !php/const Sogedial\ApiBundle\Exception\EntityNotFoundException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\DeleteEntityException: !php/const Sogedial\ApiBundle\Exception\DeleteEntityException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\InsertEntityException: !php/const Sogedial\ApiBundle\Exception\InsertEntityException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\UpdateEntityException: !php/const Sogedial\ApiBundle\Exception\UpdateEntityException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\CartEmptyException: !php/const Sogedial\ApiBundle\Exception\CartEmptyException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\OrderForbiddenException: !php/const Sogedial\ApiBundle\Exception\OrderForbiddenException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\ParametersException: !php/const Sogedial\ApiBundle\Exception\ParametersException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\UnauthorizedException: !php/const Sogedial\ApiBundle\Exception\UnauthorizedException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\BadRequestException: !php/const Sogedial\ApiBundle\Exception\BadRequestException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\ForbiddenException: !php/const Sogedial\ApiBundle\Exception\ForbiddenException::STATUS_CODE
            # Sogedial\ApiBundle\Exception\UploadException: !php/const Sogedial\ApiBundle\Exception\UploadException::STATUS_CODE
        messages:
            # 'Sogedial\ApiBundle\Exception\EntityNotFoundException': true
            # 'Sogedial\ApiBundle\Exception\DeleteEntityException': true
            # 'Sogedial\ApiBundle\Exception\InsertEntityException': true
            # 'Sogedial\ApiBundle\Exception\UpdateEntityException': true
            # 'Sogedial\ApiBundle\Exception\CartEmptyException': true
            # 'Sogedial\ApiBundle\Exception\OrderForbiddenException': true
            # 'Sogedial\ApiBundle\Exception\ParametersException': true
            # 'Sogedial\ApiBundle\Exception\UnauthorizedException': true
            # 'Sogedial\ApiBundle\Exception\BadRequestException': true
            # 'Sogedial\ApiBundle\Exception\ForbiddenException': true
            # 'Sogedial\ApiBundle\Exception\UploadException': true

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json'}
            #- { path: '^/', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', stop: true }
            - { path: '^/api', stop: true }

#resolve error when update inexist entity
jms_serializer:
    object_constructors:
        doctrine:
            fallback_strategy: 'exception'