framework:
    secret: '%env(APP_SECRET)%'
    form: { enabled: true }
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

#fos_oauth_server:
    # db_driver: orm       # Drivers available: orm, mongodb, or propel
    # client_class:        App\Entity\Client
    # access_token_class:  App\Entity\AccessToken
    # refresh_token_class: App\Entity\RefreshToken
    # auth_code_class:     App\Entity\AuthCode
    # service:
    #     user_provider: sogedial.oauth.user_provider
