sogedial_api:
    resource: "../src/Controller/"
    type:     annotation
    prefix:   /
# fos_oauth_server_token:
#     resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

# fos_oauth_server_authorize:
#     resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# auth_server_auth_login:
#     path:  /oauth/v3/auth_login
#     defaults: { _controller: OAuthBundle:Security:login }

# oauth_server_auth_login_check:
#     path:  /oauth/v3/auth_login_check

# logout:
#     path: /oauth/v3/auth_logout
